src/objects/Exceptions__c.object
<CustomObject>
    <fields>
        <fullName>Class_Or_Trigger_Name__c</fullName>
        <label>Class Or Trigger Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Exception_Type__c</fullName>
        <label>Exception Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method_Or_Block_Name__c</fullName>
        <label>Method Or Block Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Exception</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Exception ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ExceptionLogClass.cls
global class ExceptionLogClass {
	/**
	  * 
	**/
	@future
 	public static void createErrorRecord(	String objectName, String className, String methodName,
 											String errorMessage, String exceptionType, String stackTrace){
    	Exceptions__c errorRecord = new Exceptions__c();
     	
     	errorRecord.Object__c					= objectName;
     	errorRecord.Class_Or_Trigger_Name__c	= className;
     	errorRecord.Method_Or_Block_Name__c		= methodName;
     	errorRecord.Error_Message__c 			= errorMessage;
     	errorRecord.Exception_Type__c 			= exceptionType;
     	errorRecord.Stack_Trace__c 				= stackTrace;
     	
     	Database.insert(errorRecord,false);
 	}
}