src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Approver_Action__c</fullName>
        <label>Approver Action</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resubmit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dropped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Are_Brands_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Are the key brands for this seller approved in brand registry</description>
        <inlineHelpText>Are the key brands for this seller approved in brand registry</inlineHelpText>
        <label>Are Brands Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Are_templates_open__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Tick this after ensuring that verticals that this sellers will sell are Open.
If not, do not select.</description>
        <inlineHelpText>http://goo.gl/e8NaF7  See here if verticals are ready</inlineHelpText>
        <label>Are templates open</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hub_Name__c</fullName>
        <formula>Pickup_Pincode__r.Hub_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Hub Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PickupPincode__c</fullName>
        <inlineHelpText>The pincode of the hub for pickup</inlineHelpText>
        <label>PickupPincode_old</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pickup_Pincode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pickup Pincode</label>
        <referenceTo>PincodeHubMapping__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seller_Registration_Email__c</fullName>
        <label>Seller Registration Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SuperCategory__c</fullName>
        <label>SuperCategory</label>
        <picklist>
            <picklistValues>
                <fullName>BGM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Softlines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-Test</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VAT_Status__c</fullName>
        <label>VAT Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Applied For</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Needed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Hub_Name__c</fullName>
        <label>Hub Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pickup_Pincode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pickup Pincode</label>
        <referenceTo>PincodeHubMapping__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seller_Registration_Email__c</fullName>
        <externalId>true</externalId>
        <label>Seller Registration Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SuperCategory__c</fullName>
        <label>SuperCategory</label>
        <picklist>
            <picklistValues>
                <fullName>Softlines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BGM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/PincodeHubMapping__c.object
<CustomObject>
    <fields>
        <fullName>Hub_Name__c</fullName>
        <label>Hub Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Pincode Hub Mapping</label>
    <nameField>
        <label>Pickup Pin Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pincode Hub Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/updateHubOnInsertTriggerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 */
@isTest
private class updateHubOnInsertTriggerTest {

    static testMethod void HubUploadTest() {
    	
    	Profile profileBDAM = [SELECT Id FROM Profile WHERE Name='BD AM']; 
        User userBDAM = new User(   Alias = 'BDAM', Email='userBDAM@flipkart.com',LastName='Test SM', 
                                    ProfileId = profileBDAM.Id, UserName='userBDAM@flipkart.com',
                                    EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US', 
                                    LocaleSidKey='en_US', TimeZoneSidKey='Asia/Kolkata');
                                    
    	List<Lead> leadTest = new List<Lead>();
        
        PincodeHubMapping__c pin = new PincodeHubMapping__c();
        pin.Name = '112';
        pin.Hub_Name__c = 'Test Hub';
        insert pin;
        
    	leadTest.add(new Lead(Company='Test1',FirstName='Test1',LastName='Test1', Temp_Region__c = 'Goa', PickupPincode__c='111',Pickup_Pincode__c = pin.Id));
    	leadTest.add(new Lead(Company='Test2',FirstName='Test2',LastName='Test2', Temp_Region__c = 'Goa', PickupPincode__c='111',Pickup_Pincode__c = pin.Id));
    	leadTest.add(new Lead(Company='Test3',FirstName='Test3',LastName='Test3', Temp_Region__c = 'Goa', PickupPincode__c='222',Pickup_Pincode__c = pin.Id));
    	leadTest.add(new Lead(Company='Test4',FirstName='Test4',LastName='Test4', Temp_Region__c = 'Goa', PickupPincode__c='111',Pickup_Pincode__c = pin.Id));
    	insert leadTest;
    	
    	Lead l = new Lead(Company='Test5',FirstName='Test5',LastName='Test5', Temp_Region__c = 'Goa', PickupPincode__c='111', Status= 'Open',Pickup_Pincode__c = pin.Id);
    	l.Seller_Registration_Email__c = 'AAA@test.com';
    	l.SuperCategory__c = 'BGM'; 
		l.VAT_Status__c = 'Not Needed'; 
		l.Are_templates_open__c = TRUE;
		l.Are_Brands_Approved__c = TRUE; 
		l.Phone = '2222';
		l.Approver_Action__c ='Approved';
    	
    	insert l;
    	
    	/*Database.LeadConvert lc = new database.LeadConvert();
		lc.setLeadId(l.id);
		lc.setDoNotCreateOpportunity(true);
		lc.setOwnerId(userBDAM.Id);
		lc.setConvertedStatus('Converted');
		
		Database.LeadConvertResult lcr = Database.convertLead(lc);
		System.assert(lcr.isSuccess());*/
    	
    	Account testAccount = new Account(Name = 'Test Account');        
        insert testAccount;
        
        PincodeHubMapping__c pin111 = new PincodeHubMapping__c(Name = '111', Hub_Name__c = 'Test Hub');
        insert pin111;
        
        PincodeHubMapping__c pin222 = new PincodeHubMapping__c(Name = '222', Hub_Name__c = 'Test Hub');
        insert pin222;
        
    	List<Opportunity> oppList = new List<Opportunity>();
    	oppList.add(new Opportunity(  Name = 'Test1',AccountId = testAccount.Id,StageName = 'Candidate',CloseDate = date.parse('01/10/2014'), Pickup_Pincode__c='111',
                                                        Seller_Registration_Email__c = 'test@testmail.com',
                                                        Pickup_Area_Pincode__c = pin111.Id ));
    	oppList.add(new Opportunity(  Name = 'Test2',AccountId = testAccount.Id,StageName = 'Candidate',CloseDate = date.parse('01/10/2014'), Pickup_Pincode__c='111',
                                                        Seller_Registration_Email__c = 'test@testmail.com',
                                                        Pickup_Area_Pincode__c = pin111.Id ));
    	oppList.add(new Opportunity(  Name = 'Test3',AccountId = testAccount.Id,StageName = 'Candidate',CloseDate = date.parse('01/10/2014'), Pickup_Pincode__c='222',
                                                        Seller_Registration_Email__c = 'test@testmail.com',
                                                        Pickup_Area_Pincode__c = pin222.Id ));
    	oppList.add(new Opportunity(  Name = 'Test4',AccountId = testAccount.Id,StageName = 'Candidate',CloseDate = date.parse('01/10/2014'), Pickup_Pincode__c='111',
                                                        Seller_Registration_Email__c = 'test@testmail.com',
                                                        Pickup_Area_Pincode__c = pin111.Id ));
    	oppList.add(new Opportunity(  Name = 'Test5',AccountId = testAccount.Id,StageName = 'Candidate',CloseDate = date.parse('01/10/2014'), Pickup_Pincode__c='111',
                                                        Seller_Registration_Email__c = 'test@testmail.com',
                                                        Pickup_Area_Pincode__c = pin111.Id ));
    	insert oppList;
    	
    	PincodeHubMapping__c pin1 = new PincodeHubMapping__c();
    	pin1.Name = '111';pin1.Hub_Name__c = 'ABD';
    	insert pin1;
    	
    	List<Lead> leadPrintList = [	SELECT Id,Name, PickupPincode__c,Pickup_Pincode__c,Hub_Name__c 
							FROM Lead ];
	
		List<Opportunity> oppPrintList = [	SELECT Id,Name, Pickup_Pincode__c,Pickup_Area_Pincode__c, Hub_Name__c
									FROM Opportunity];
    	
    	for(Lead lead : leadPrintList){
    		System.debug('1-Lead Name'+lead.Name);
    		System.debug('1-lead.Pickup_Pincode__c'+lead.Pickup_Pincode__c);
    		System.debug('1-lead.Hub_Name__c'+lead.Hub_Name__c);
    	}
    	
    	for(Opportunity opp : oppPrintList){
    		System.debug('1- Opp Name'+opp.Name);
    		System.debug('1-opp.Pickup_Area_Pincode__c'+opp.Pickup_Area_Pincode__c);
    		System.debug('1-opp.Hub_Name__c'+opp.Hub_Name__c);
    	}
    	
    	PincodeHubMapping__c pin11 = new PincodeHubMapping__c();
    	pin11.Name = '222';pin11.Hub_Name__c = 'XYZ';
    	insert pin11;
    	
    	List<Lead> leadPrintList2 = [	SELECT Id,Name, PickupPincode__c,Pickup_Pincode__c,Hub_Name__c 
							FROM Lead ];
	
		List<Opportunity> oppPrintList2 = [	SELECT Id,Name, Pickup_Pincode__c,Pickup_Area_Pincode__c, Hub_Name__c
									FROM Opportunity];
    	
    	for(Lead lead : leadPrintList2){
    		System.debug('2-Lead Name'+lead.Name);
    		System.debug('2-lead.Pickup_Pincode__c'+lead.Pickup_Pincode__c);
    		System.debug('2-lead.Hub_Name__c'+lead.Hub_Name__c);
    	}
    	
    	for(Opportunity opp : oppPrintList2){
    		System.debug('2- Opp Name'+opp.Name);
    		System.debug('2-opp.Pickup_Area_Pincode__c'+opp.Pickup_Area_Pincode__c);
    		System.debug('2-opp.Hub_Name__c'+opp.Hub_Name__c);
    	}
    }
}