src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Expected_TAT__c</fullName>
        <defaultValue>25</defaultValue>
        <label>Expected TAT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TAT_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TAT Profile</label>
        <referenceTo>TAT_Profile__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Seller_TAT_Breach__c.object
<CustomObject>
    <fields>
        <fullName>Estimated_Closure_Date__c</fullName>
        <label>Estimated Closure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ideal_Closure_Date__c</fullName>
        <label>Ideal Closure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Breach_Date__c</fullName>
        <label>Next Breach Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Seller TAT Breach</relationshipLabel>
        <relationshipName>Seller_TAT_Breach</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TAT_Stage_Profile_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TAT Stage Profile ID</label>
        <referenceTo>TAT_Stage_Profile__c</referenceTo>
        <relationshipLabel>Seller TAT Breach</relationshipLabel>
        <relationshipName>Seller_TAT_Breach</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Seller TAT Breach</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seller TAT Breach</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TAT_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TAT_Profile__c</fullName>
        <label>TAT Profile</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>TAT Profile</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TAT Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TAT_Stage__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TAT_Stage__c</fullName>
        <label>TAT Stage</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>TAT Stage</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TAT Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TAT_Stage_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TAT_Profile_ID__c</fullName>
        <label>TAT Profile ID</label>
        <referenceTo>TAT_Profile__c</referenceTo>
        <relationshipLabel>TAT Stage Profile</relationshipLabel>
        <relationshipName>TAT_Stage_Profile</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TAT_Profile_Spec__c</fullName>
        <label>TAT Profile Spec</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TAT_Stage_ID__c</fullName>
        <label>TAT Stage ID</label>
        <referenceTo>TAT_Stage__c</referenceTo>
        <relationshipLabel>TAT Stage Profile</relationshipLabel>
        <relationshipName>TAT_Stage_Profile</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>TAT Stage Profile</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TAT Stage Profile</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BatchProcessingExistingTATDataTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 */
@isTest
public class BatchProcessingExistingTATDataTest {

    static testMethod void batchProcessingTestOne() {
        Test.startTest();
        BatchProcessingExistingTATDataClass batch = new BatchProcessingExistingTATDataClass();
        Database.executeBatch(batch,50);
        Test.stopTest();
    } 
    
    static testMethod void batchProcessingTester(){
    	List<Holiday> holidaysList = [Select h.ActivityDate From Holiday h];
    	Opportunity opp = UtilityClassTest.createOpportunityTestRecord();
        opp.Expected_TAT__c = Constants.TAT_13;
        opp.StageName = Constants.OPP_STAGE_READY_TO_INVITE;
        update opp;
        
        opp.StageName = Constants.OPP_STAGE_INVITED;
        update opp;
        
    	TATHelperTest.createTATStageProfile18TestData();
    	List<TAT_Stage_Profile__c> TATStageProfileList = [SELECT Id,TAT_Profile_Spec__c,TAT_Profile_ID__r.TAT_Profile__c,
                                                             TAT_Stage_ID__r.Name,TAT_Stage_ID__r.TAT_Stage__c,
                                                             TAT_Profile_ID__r.Name
                                                      FROM TAT_Stage_Profile__c  where active__c = TRUE];
    	
    	List<Seller_TAT_Breach__c> sellerTATList = new List<Seller_TAT_Breach__c>();
        Date actualStartDate = Date.parse('20/08/2013');	
        Date closureDate = actualStartDate - 1;
        Date nextBreachDate;
        
        for(TAT_Stage_Profile__c tsp: TATStageProfileList){
        	System.debug('In TAT Stage Profile loop');
            closureDate = UtilityClass.addDaysExcludingSundaysHolidays(closureDate,
                                                                    Integer.valueOf(tsp.TAT_Profile_Spec__c),
                                                                    holidaysList);
            nextBreachDate = UtilityClass.addDaysExcludingSundaysHolidays(closureDate,1,holidaysList);
            Seller_TAT_Breach__c sellerTAT = new Seller_TAT_Breach__c();
            sellerTAT.TAT_Stage_Profile_ID__c = tsp.Id;
            sellerTAT.Opportunity__c = opp.Id;
            sellerTAT.Ideal_Closure_Date__c = closureDate;
            sellerTAT.Next_Breach_Date__c = nextBreachDate;
            sellerTAT.Estimated_Closure_Date__c = closureDate;
            sellerTATList.add(sellerTAT);
        }
        insert sellerTATList;
        
        Test.startTest();
        BatchProcessingExistingTATDataClass batch = new BatchProcessingExistingTATDataClass();
        Database.executeBatch(batch,50);
        Test.stopTest();
    }   
}