src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Expected_TAT__c</fullName>
        <defaultValue>25</defaultValue>
        <label>Expected TAT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hub_Name__c</fullName>
        <label>Hub Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seller_Registration_Email__c</fullName>
        <externalId>true</externalId>
        <label>Seller Registration Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>TAT_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TAT Profile</label>
        <referenceTo>TAT_Profile__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/PincodeHubMapping__c.object
<CustomObject>
    <fields>
        <fullName>Hub_Name__c</fullName>
        <label>Hub Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Pincode Hub Mapping</label>
    <nameField>
        <label>Pickup Pin Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pincode Hub Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TAT_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TAT_Profile__c</fullName>
        <label>TAT Profile</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>TAT Profile</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TAT Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TAT_Stage__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TAT_Stage__c</fullName>
        <label>TAT Stage</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>TAT Stage</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TAT Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TAT_Stage_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TAT_Profile_ID__c</fullName>
        <label>TAT Profile ID</label>
        <referenceTo>TAT_Profile__c</referenceTo>
        <relationshipLabel>TAT Stage Profile</relationshipLabel>
        <relationshipName>TAT_Stage_Profile</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TAT_Profile_Spec__c</fullName>
        <label>TAT Profile Spec</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TAT_Stage_ID__c</fullName>
        <label>TAT Stage ID</label>
        <referenceTo>TAT_Stage__c</referenceTo>
        <relationshipLabel>TAT Stage Profile</relationshipLabel>
        <relationshipName>TAT_Stage_Profile</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>TAT Stage Profile</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TAT Stage Profile</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/InsertUpdateSellerTATBreachBatchTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 */
@isTest
private class InsertUpdateSellerTATBreachBatchTest {

   @isTest(seeAllData=false)
    static void myUnitTest() {
    	
    	 Opportunity opp = UtilityClassTest.createOpportunityTestRecord();
        opp.Expected_TAT__c = Constants.TAT_13;
        opp.StageName = Constants.OPP_STAGE_READY_TO_INVITE;
        update opp;
        
        opp.StageName = Constants.OPP_STAGE_INVITED;
        update opp;
        // TO DO: implement unit test
        Test.startTest();
        InsertUpdateSellerTATBreachBatchClass stbClass = new InsertUpdateSellerTATBreachBatchClass();
        Database.executeBatch(stbClass,50);
        Test.stopTest();
    }
    
    @isTest(seeAllData=false)
    static void myUnitTest2() {
    	
    	 Account testAccount = new Account(Name = 'Test Account');        
        insert testAccount;
        
        PincodeHubMapping__c pin = new PincodeHubMapping__c(Name = '1020301', Hub_Name__c = 'Test Hub');
        insert pin;
        
        Opportunity opp = new Opportunity(  Name = 'Test Opportunity',
                                                        AccountId = testAccount.Id,
                                                        StageName = Constants.OPP_STAGE_CANDIDATE,
                                                        CloseDate = date.parse('01/10/2014'),
                                                        Seller_Registration_Email__c = 'test@testmail.com',
                                                        Pickup_Area_Pincode__c = pin.Id //,
                                                        //TAT_Profile__c = tatProfile.Id
                                                      );
        insert opp;
        System.runAs(UtilityClassTest.userWithBDOMProfile()) {
	        opp.StageName = Constants.OPP_STAGE_READY_TO_ONBOARD;
	        update opp;
        }
        
        opp.Expected_TAT__c = Constants.TAT_13;
        opp.StageName = Constants.OPP_STAGE_READY_TO_INVITE;
        update opp;
        
        opp.StageName = Constants.OPP_STAGE_INVITED;
        update opp;
        
        opp.StageName = Constants.OPP_STAGE_MIN_SKU_CREATION;
        update opp;
        
        // TO DO: implement unit test
        Test.startTest();
        InsertUpdateSellerTATBreachBatchClass stbClass = new InsertUpdateSellerTATBreachBatchClass();
        Database.executeBatch(stbClass,50);
        Test.stopTest();
    }
    
    @isTest(seeAllData=true)
    static List<TAT_Stage__c> getTATStageInfo(){
    	
    	List<TAT_Stage__c> tatStageList = [SELECT Id, TAT_Stage__c, Active__c FROM TAT_Stage__c ORDER BY Id];
    	
    	return tatStageList;
    	
    }
    
    @isTest(seeAllData=true)
    static List<TAT_Profile__c> getTATProfileInfo(){
    	List<TAT_Profile__c> tatProfileList = [SELECT Id, TAT_Profile__c, Active__c FROM TAT_Profile__c ORDER BY Id];
    	
    	return tatProfileList;
    }
    
     @isTest(seeAllData=true)
    static List<TAT_Stage_Profile__c> getTATStageProfileInfo(){
    	List<TAT_Stage_Profile__c> TATStageProfileList = [SELECT Id,TAT_Profile_Spec__c,TAT_Profile_ID__r.TAT_Profile__c,
                                                             TAT_Stage_ID__r.Name,TAT_Stage_ID__r.TAT_Stage__c,
                                                             TAT_Profile_ID__r.Name
                                                      FROM TAT_Stage_Profile__c  where active__c = TRUE];
    	
    	return TATStageProfileList;
    }
    
    
}