src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Expected_TAT__c</fullName>
        <defaultValue>25</defaultValue>
        <label>Expected TAT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TAT_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TAT Profile</label>
        <referenceTo>TAT_Profile__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Seller_TAT_Breach__c.object
<CustomObject>
    <fields>
        <fullName>Estimated_Closure_Date__c</fullName>
        <label>Estimated Closure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ideal_Closure_Date__c</fullName>
        <label>Ideal Closure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Breach_Date__c</fullName>
        <label>Next Breach Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Seller TAT Breach</relationshipLabel>
        <relationshipName>Seller_TAT_Breach</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TAT_Stage_Profile_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TAT Stage Profile ID</label>
        <referenceTo>TAT_Stage_Profile__c</referenceTo>
        <relationshipLabel>Seller TAT Breach</relationshipLabel>
        <relationshipName>Seller_TAT_Breach</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Seller TAT Breach</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seller TAT Breach</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TAT_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TAT_Profile__c</fullName>
        <label>TAT Profile</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>TAT Profile</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TAT Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TAT_Stage__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TAT_Stage__c</fullName>
        <label>TAT Stage</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>TAT Stage</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TAT Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TAT_Stage_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TAT_Profile_ID__c</fullName>
        <label>TAT Profile ID</label>
        <referenceTo>TAT_Profile__c</referenceTo>
        <relationshipLabel>TAT Stage Profile</relationshipLabel>
        <relationshipName>TAT_Stage_Profile</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TAT_Profile_Spec__c</fullName>
        <label>TAT Profile Spec</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TAT_Stage_ID__c</fullName>
        <label>TAT Stage ID</label>
        <referenceTo>TAT_Stage__c</referenceTo>
        <relationshipLabel>TAT Stage Profile</relationshipLabel>
        <relationshipName>TAT_Stage_Profile</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>TAT Stage Profile</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TAT Stage Profile</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ExistingOpportunityTATBuilderClass.cls
global class ExistingOpportunityTATBuilderClass implements Schedulable{
    global void execute(SchedulableContext ctx) {
        List<Opportunity> oppList = [	SELECT 	Id, StageName,Expected_TAT__c   
        								FROM	Opportunity
        								WHERE	StageName NOT IN ('Candidate', 'Ready to Onboard', 'Ready to Invite', 'Live')];        															
		        															
        List<Seller_TAT_Breach__c> sellerTATBreachList = [	SELECT	Id, Opportunity__c
        													FROM	Seller_TAT_Breach__c];
		
		List<Seller_TAT_Breach__c> sellerTATList = new List<Seller_TAT_Breach__c> ();
        List<Holiday> holidaysList = [Select h.ActivityDate From Holiday h];        													
        													
		List<TAT_Stage_Profile__c> TATStageProfileList = [SELECT Id,TAT_Profile_Spec__c,TAT_Profile_ID__r.TAT_Profile__c,
                                                             TAT_Stage_ID__r.Name,TAT_Stage_ID__r.TAT_Stage__c,
                                                             TAT_Profile_ID__r.Name
                                                      FROM TAT_Stage_Profile__c  where active__c = TRUE];        													
        													
        List<Opportunity> oppTATList = new List<Opportunity>();
        
        for(Opportunity opp : oppList){
        	Integer tatCounter = 0;
        	for(Seller_TAT_Breach__c stb : sellerTATBreachList ){
        		if(opp.Id == stb.Opportunity__c){
        			tatCounter++;
        		}
        	}
        	if(tatCounter == 0){
        		oppTATList.add(opp);		
        	}
        }						
        
        if(oppTATList.size() > 0){
        	List<TAT_Profile__c> tatProfileList = [SELECT Id, TAT_Profile__c FROM TAT_Profile__c];
		
			ID TAT_Profile_13_ID = null;
			ID TAT_Profile_18_ID = null;
			
			for(TAT_Profile__c tat:tatProfileList){
				if((tat.TAT_Profile__c).contains(Constants.TAT_13)){
					TAT_Profile_13_ID = tat.Id;
				}else if((tat.TAT_Profile__c).contains(Constants.TAT_18)){
					TAT_Profile_18_ID = tat.Id;
				}
			}
			
        	for(Opportunity opp : oppTATList){
        		Date actualStartDate = Date.today();//
	            Date closureDate = actualStartDate - 1;
	            Date nextBreachDate;
	            
        		ID TAT_Profile_ID = null;
        		
        		if(opp.Expected_TAT__c != null){
					if(opp.Expected_TAT__c == Constants.TAT_13 || opp.Expected_TAT__c == Constants.TAT_15){
						TAT_Profile_ID = TAT_Profile_13_ID;
					}else if(opp.Expected_TAT__c == Constants.TAT_18 || opp.Expected_TAT__c == Constants.TAT_25){
						TAT_Profile_ID = TAT_Profile_18_ID;
					}
	        		
	        		for(TAT_Stage_Profile__c tsp: TATStageProfileList){
	        			if(tsp.TAT_Profile_ID__c == TAT_Profile_ID ){
			                closureDate = UtilityClass.addDaysExcludingSundaysHolidays(closureDate,
			                                                                        Integer.valueOf(tsp.TAT_Profile_Spec__c),
			                                                                        holidaysList);
			                nextBreachDate = UtilityClass.addDaysExcludingSundaysHolidays(closureDate,1,holidaysList);
			                Seller_TAT_Breach__c sellerTAT = new Seller_TAT_Breach__c();
			                sellerTAT.TAT_Stage_Profile_ID__c = tsp.Id;
			                sellerTAT.Opportunity__c = opp.Id;
			                sellerTAT.Ideal_Closure_Date__c = closureDate;
			                sellerTAT.Next_Breach_Date__c = nextBreachDate;
			                sellerTAT.Estimated_Closure_Date__c = closureDate;
			                sellerTATList.add(sellerTAT);
		            	}
	        		}
        		}
        	}
            insert sellerTATList;
        }
    }
}