src/objects/Seller_TAT_Breach__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Closure_Date__c</fullName>
        <label>Actual Closure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Estimated_Closure_Date__c</fullName>
        <label>Estimated Closure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ideal_Closure_Date__c</fullName>
        <label>Ideal Closure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Breach_Date__c</fullName>
        <label>Next Breach Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Seller TAT Breach</relationshipLabel>
        <relationshipName>Seller_TAT_Breach</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TAT_Breach_in_Days__c</fullName>
        <label>TAT Breach in Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TAT_Stage_Profile_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TAT Stage Profile ID</label>
        <referenceTo>TAT_Stage_Profile__c</referenceTo>
        <relationshipLabel>Seller TAT Breach</relationshipLabel>
        <relationshipName>Seller_TAT_Breach</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Taken_per_Stage__c</fullName>
        <label>Time Taken per Stage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Seller TAT Breach</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seller TAT Breach</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TAT_Stage__c.object
<CustomObject>
    <fields>
        <fullName>TAT_Stage__c</fullName>
        <label>TAT Stage</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>TAT Stage</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TAT Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TAT_Stage_Profile__c.object
<CustomObject>
    <fields>
        <fullName>TAT_Profile_Spec__c</fullName>
        <label>TAT Profile Spec</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TAT_Stage_ID__c</fullName>
        <label>TAT Stage ID</label>
        <referenceTo>TAT_Stage__c</referenceTo>
        <relationshipLabel>TAT Stage Profile</relationshipLabel>
        <relationshipName>TAT_Stage_Profile</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>TAT Stage Profile</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TAT Stage Profile</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SellerTATBreachBatchUpdateClass.cls
global class SellerTATBreachBatchUpdateClass implements Database.Batchable<sObject>{

    global Database.QueryLocator start(Database.BatchableContext BC){
                        
        String query = '    SELECT  Id,Invited_Start_Date__c FROM Opportunity';                     
        
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){
        List<Opportunity> oppList = new List<Opportunity>();
        List<Seller_TAT_Breach__c> updateSellerList = new List<Seller_TAT_Breach__c>();
        List<Seller_TAT_Breach__c> sellerTATBreachList = new List<Seller_TAT_Breach__c>();
        
        List<Holiday> holidaysList = [Select h.ActivityDate From Holiday h];

        for(sObject s : scope){
            Opportunity opp = (Opportunity)s;
            updateSellerList = [SELECT  Id,Opportunity__c,Ideal_Closure_Date__c,
                                            Actual_Closure_Date__c,Next_Breach_Date__c,
                                            Estimated_Closure_Date__c,TAT_Stage_Profile_ID__r.TAT_Profile_Spec__c,
                                            TAT_Stage_Profile_ID__r.TAT_Stage_ID__r.TAT_Stage__c
                              FROM    Seller_TAT_Breach__c where  Opportunity__c = :opp.Id order by Name];
            
            for(Integer i=0; i<updateSellerList.size() ;i++){
                if(updateSellerList.get(i).Actual_Closure_Date__c != null){
                    //if(updateSellerList.get(i).Actual_Closure_Date__c != updateSellerList.get(i).Ideal_Closure_Date__c){
                        
                        if(i != 0){
                            updateSellerList.get(i).Time_Taken_per_Stage__c = UtilityClass.daysBetweenExcludingSundaysHolidays( updateSellerList.get(i-1).Actual_Closure_Date__c, 
                                                                                                                                updateSellerList.get(i).Actual_Closure_Date__c, 
                                                                                                                                holidaysList);
                        }else{
                            Date tempDate = null;
                            
                            if(opp.Invited_Start_Date__c != null){
                                tempDate = opp.Invited_Start_Date__c;
                            }
                            
                            if(tempDate != null)
                            updateSellerList.get(i).Time_Taken_per_Stage__c = UtilityClass.daysBetweenExcludingSundaysHolidays( tempDate, 
                                                                                                                                updateSellerList.get(i).Actual_Closure_Date__c, 
                                                                                                                                holidaysList);
                        }
                    //}
                    
                    if(updateSellerList.get(i).Actual_Closure_Date__c != null){
                        if(updateSellerList.get(i).Actual_Closure_Date__c >= updateSellerList.get(i).Next_Breach_Date__c ){
                            updateSellerList.get(i).TAT_Breach_in_Days__c = UtilityClass.daysBetweenExcludingSundaysHolidays(   updateSellerList.get(i).Next_Breach_Date__c,
                                                                                                            updateSellerList.get(i).Actual_Closure_Date__c,
                                                                                                            holidaysList
                                                                                                        ) + 1;
                        }else{
                            updateSellerList.get(i).TAT_Breach_in_Days__c = 0;
                        }
                    }
                }
            }
            sellerTATBreachList.addAll(updateSellerList);
        }
    
        update sellerTATBreachList;
    }

    global void finish(Database.BatchableContext BC){
    
    }
}